-- Portfolio v2: accounts with product histories, per-card credit usage, and
-- direct (RLS-protected) client access. The v1 tables are kept as legacy_* so
-- nothing is lost; the sheet importer populates the new tables.

alter table if exists public.benefit_usage rename to legacy_benefit_usage;
alter table if exists public.benefits rename to legacy_benefits;
alter table if exists public.accounts rename to legacy_accounts;
alter table if exists public.card_types rename to legacy_card_types;

-- Cardholders. Separate from sign-in members: a member signs in, a person holds cards.
create table public.people (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  email text,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  unique (household_id, name),
  unique (household_id, id)
);

-- Card types, e.g. "Amex Business Platinum". `slug` is the short name used in the sheet.
create table public.products (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  slug text not null check (length(trim(slug)) > 0),
  name text not null check (length(trim(name)) > 0),
  issuer text not null default 'Other',
  kind text not null default 'personal' check (kind in ('personal', 'business', 'other')),
  annual_fee_cents integer not null default 0 check (annual_fee_cents >= 0),
  created_at timestamptz not null default now(),
  unique (household_id, slug),
  unique (household_id, id)
);

-- One row per credit line: opened once by an application, closed at most once.
-- Upgrades and downgrades are rows in account_products, not new accounts.
create table public.accounts (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  person_id bigint not null,
  applied_on date,
  approved_on date,
  opened_via text not null default 'applied' check (opened_via in ('applied', 'referral', 'nll_offer', 'product_change', 'other')),
  status text not null default 'pending' check (status in ('pending', 'open', 'closed', 'declined')),
  closed_on date,
  bonus_amount integer check (bonus_amount is null or bonus_amount > 0),
  bonus_unit text check (bonus_unit is null or bonus_unit in ('points', 'cash', 'nights')),
  bonus_spend_cents integer check (bonus_spend_cents is null or bonus_spend_cents >= 0),
  bonus_months integer check (bonus_months is null or bonus_months > 0),
  bonus_earned boolean not null default false,
  note text,
  source_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (household_id, id),
  unique (household_id, id, person_id),
  constraint accounts_person_fkey foreign key (household_id, person_id) references public.people(household_id, id) on delete restrict,
  constraint accounts_open_needs_approval check (status not in ('open', 'closed') or approved_on is not null),
  constraint accounts_closed_needs_date check (status <> 'closed' or closed_on is not null)
);

-- The products an account has been over time. `number` is the per-person,
-- per-card-type sequence ("CSR #5"); it is stored so it never silently shifts.
create table public.account_products (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  account_id bigint not null,
  person_id bigint not null,
  product_id bigint not null,
  number integer check (number is null or number > 0),
  started_on date not null,
  ended_on date,
  change text not null default 'opened' check (change in ('opened', 'upgrade', 'downgrade')),
  annual_fee_cents integer not null default 0 check (annual_fee_cents >= 0),
  last4 text check (last4 is null or last4 ~ '^[0-9]{4,5}$'),
  created_at timestamptz not null default now(),
  unique (household_id, id),
  constraint account_products_account_fkey foreign key (household_id, account_id, person_id)
    references public.accounts(household_id, id, person_id) on update cascade on delete cascade,
  constraint account_products_product_fkey foreign key (household_id, product_id)
    references public.products(household_id, id) on delete restrict,
  constraint account_products_dates check (ended_on is null or ended_on >= started_on)
);

create unique index account_products_number_unique
  on public.account_products(household_id, person_id, product_id, number) where number is not null;
create unique index account_products_one_current
  on public.account_products(account_id) where ended_on is null;

-- Recurring statement credits defined on a card type.
create table public.credits (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  product_id bigint not null,
  name text not null check (length(trim(name)) > 0),
  amount_cents integer not null check (amount_cents > 0),
  cadence text not null check (cadence in ('monthly', 'quarterly', 'semiannual', 'calendar_year', 'card_year')),
  remind boolean not null default true,
  starts_on date,
  ends_on date,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  unique (household_id, id),
  constraint credits_product_fkey foreign key (household_id, product_id) references public.products(household_id, id) on delete cascade
);

-- A credit used (fully or partly) on a specific card during one period.
create table public.credit_uses (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  credit_id bigint not null,
  account_product_id bigint not null,
  period_key text not null,
  amount_cents integer not null check (amount_cents > 0),
  used_on date,
  recorded_by text,
  source text not null default 'manual' check (source in ('manual', 'import', 'plaid')),
  note text,
  created_at timestamptz not null default now(),
  constraint credit_uses_credit_fkey foreign key (household_id, credit_id) references public.credits(household_id, id) on delete cascade,
  constraint credit_uses_holding_fkey foreign key (household_id, account_product_id) references public.account_products(household_id, id) on delete cascade
);

-- "Not enrolled": a credit that should not be tracked on a specific card.
create table public.credit_opt_outs (
  household_id uuid not null references public.households(id) on delete cascade,
  credit_id bigint not null,
  account_product_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (credit_id, account_product_id),
  constraint credit_opt_outs_credit_fkey foreign key (household_id, credit_id) references public.credits(household_id, id) on delete cascade,
  constraint credit_opt_outs_holding_fkey foreign key (household_id, account_product_id) references public.account_products(household_id, id) on delete cascade
);

create index idx_accounts_household_person on public.accounts(household_id, person_id, status);
create index idx_account_products_account on public.account_products(household_id, account_id);
create index idx_credits_product on public.credits(household_id, product_id);
create index idx_credit_uses_lookup on public.credit_uses(household_id, credit_id, account_product_id, period_key);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger accounts_touch_updated_at before update on public.accounts
  for each row execute function public.touch_updated_at();

-- Row-level security: members of a household manage that household's rows.
do $$
declare
  item text;
begin
  foreach item in array array['people', 'products', 'accounts', 'account_products', 'credits', 'credit_uses', 'credit_opt_outs'] loop
    execute format('alter table public.%I enable row level security', item);
    execute format(
      'create policy "members manage %s" on public.%I for all using (public.is_cardfolio_member(household_id)) with check (public.is_cardfolio_member(household_id))',
      item, item
    );
    execute format('grant select, insert, update, delete on public.%I to authenticated, service_role', item);
  end loop;
end;
$$;

grant select on public.households, public.household_members to authenticated;

-- Live updates for both cardholders' browsers.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table
      public.accounts, public.account_products, public.credits, public.credit_uses,
      public.credit_opt_outs, public.products, public.people, public.action_rules;
  end if;
end;
$$;

-- Action rules now name card types by slug.
update public.action_rules set conditions = jsonb_set(conditions, '{cardNames}', '["biz plat", "biz gold"]'::jsonb)
  where name = 'Amex no-lifetime-language window';
update public.action_rules set conditions = jsonb_set(conditions, '{cardNames}', '["cic"]'::jsonb)
  where name = 'Chase Ink Cash velocity window';
update public.action_rules set conditions = jsonb_set(conditions, '{cardNames}', '["redcard"]'::jsonb)
  where name = 'Target RedCard reapply window';

create or replace function public.reset_cardfolio_sequences()
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  item text;
begin
  foreach item in array array['people', 'products', 'accounts', 'account_products', 'credits', 'credit_uses'] loop
    execute format(
      'select setval(pg_get_serial_sequence(%L, %L), greatest(coalesce((select max(id) from public.%I), 0) + 1, 1), false)',
      'public.' || item,
      'id',
      item
    );
  end loop;
end;
$$;

revoke all on function public.reset_cardfolio_sequences() from public, anon, authenticated;
grant execute on function public.reset_cardfolio_sequences() to service_role;
