create extension if not exists pgcrypto;

create table if not exists public.households (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.household_members (
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now(),
  primary key (household_id, user_id),
  unique (user_id)
);

create table if not exists public.household_invitations (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  email text not null,
  role text not null default 'member' check (role in ('owner', 'member')),
  invited_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (household_id, email)
);

create table if not exists public.app_meta (
  household_id uuid not null references public.households(id) on delete cascade,
  key text not null,
  value text not null,
  primary key (household_id, key)
);

create table if not exists public.card_types (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null,
  issuer text not null default 'Other',
  kind text not null default 'personal',
  annual_fee integer not null default 0 check (annual_fee >= 0),
  created_at timestamptz not null default now(),
  unique (household_id, name),
  unique (household_id, id)
);

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  owner text not null,
  card_type_id bigint not null,
  kind text not null,
  card_index text,
  applied_on date,
  approved_on date,
  opened_how text,
  offer text,
  annual_fee integer not null default 0 check (annual_fee >= 0),
  bonus_received boolean not null default false,
  status text not null default 'pending' check (status in ('active', 'closed', 'pending', 'declined')),
  closed_on date,
  closed_how text,
  source_row integer,
  created_at timestamptz not null default now(),
  unique (household_id, id),
  constraint accounts_card_type_id_fkey foreign key (household_id, card_type_id) references public.card_types(household_id, id) on delete restrict
);

create table if not exists public.benefits (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  card_type_id bigint not null,
  name text not null,
  amount integer not null default 0 check (amount >= 0),
  frequency text not null default 'calendar year',
  unique (household_id, id),
  constraint benefits_card_type_id_fkey foreign key (household_id, card_type_id) references public.card_types(household_id, id) on delete cascade
);

create table if not exists public.benefit_usage (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  account_id bigint not null,
  benefit_id bigint not null,
  period_key text not null,
  used boolean not null default false,
  used_on date,
  unique (account_id, benefit_id, period_key),
  constraint benefit_usage_account_id_fkey foreign key (household_id, account_id) references public.accounts(household_id, id) on delete cascade,
  constraint benefit_usage_benefit_id_fkey foreign key (household_id, benefit_id) references public.benefits(household_id, id) on delete cascade
);

create index if not exists idx_accounts_household_owner_status on public.accounts(household_id, owner, status);
create index if not exists idx_accounts_household_card_type_status on public.accounts(household_id, card_type_id, status);
create unique index if not exists idx_accounts_household_source_row on public.accounts(household_id, source_row) where source_row is not null;
create index if not exists idx_benefits_household_card_type on public.benefits(household_id, card_type_id);
create index if not exists idx_usage_household_period on public.benefit_usage(household_id, period_key, used);
create index if not exists idx_invitations_household_email on public.household_invitations(household_id, lower(email));

insert into public.households (id, slug, name)
values ('00000000-0000-4000-8000-00000000cafd', 'primary', 'Cardfolio')
on conflict (slug) do nothing;

create or replace function public.is_cardfolio_member(target_household_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.household_members
    where household_id = target_household_id and user_id = auth.uid()
  );
$$;

create or replace function public.is_cardfolio_owner(target_household_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.household_members
    where household_id = target_household_id and user_id = auth.uid() and role = 'owner'
  );
$$;

alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.household_invitations enable row level security;
alter table public.app_meta enable row level security;
alter table public.card_types enable row level security;
alter table public.accounts enable row level security;
alter table public.benefits enable row level security;
alter table public.benefit_usage enable row level security;

create policy "members read households" on public.households for select using (public.is_cardfolio_member(id));
create policy "members read memberships" on public.household_members for select using (public.is_cardfolio_member(household_id));
create policy "owners manage invitations" on public.household_invitations for all using (public.is_cardfolio_owner(household_id)) with check (public.is_cardfolio_owner(household_id));
create policy "members read app metadata" on public.app_meta for select using (public.is_cardfolio_member(household_id));
create policy "members manage card types" on public.card_types for all using (public.is_cardfolio_member(household_id)) with check (public.is_cardfolio_member(household_id));
create policy "members manage accounts" on public.accounts for all using (public.is_cardfolio_member(household_id)) with check (public.is_cardfolio_member(household_id));
create policy "members manage benefits" on public.benefits for all using (public.is_cardfolio_member(household_id)) with check (public.is_cardfolio_member(household_id));
create policy "members manage benefit usage" on public.benefit_usage for all using (public.is_cardfolio_member(household_id)) with check (public.is_cardfolio_member(household_id));

create or replace function public.reset_cardfolio_sequences()
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  item text;
begin
  foreach item in array array['card_types', 'accounts', 'benefits', 'benefit_usage'] loop
    execute format(
      'select setval(pg_get_serial_sequence(%L, %L), greatest(coalesce((select max(id) from public.%I), 0) + 1, 1), false)',
      'public.' || item,
      'id',
      item
    );
  end loop;
end;
$$;

revoke all on function public.reset_cardfolio_sequences() from public, anon, authenticated;
grant execute on function public.reset_cardfolio_sequences() to service_role;

revoke all on function public.is_cardfolio_member(uuid) from public;
revoke all on function public.is_cardfolio_owner(uuid) from public;
grant execute on function public.is_cardfolio_member(uuid) to authenticated, service_role;
grant execute on function public.is_cardfolio_owner(uuid) to authenticated, service_role;
