-- Push reminders: one row per browser/device that turned reminders on, and a
-- log so the daily job never notifies twice for the same day.

create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  last_sent_at timestamptz
);

create index idx_push_subscriptions_household on public.push_subscriptions(household_id);

alter table public.push_subscriptions enable row level security;

-- Members manage only their own devices; the reminder job uses the service role.
create policy "members manage own push subscriptions" on public.push_subscriptions for all
  using (user_id = auth.uid() and public.is_cardfolio_member(household_id))
  with check (user_id = auth.uid() and public.is_cardfolio_member(household_id));

grant select, insert, update, delete on public.push_subscriptions to authenticated, service_role;

create table public.reminder_log (
  household_id uuid not null references public.households(id) on delete cascade,
  sent_on date not null,
  summary text not null,
  devices integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (household_id, sent_on)
);

alter table public.reminder_log enable row level security;

create policy "members read reminder log" on public.reminder_log for select
  using (public.is_cardfolio_member(household_id));

grant select on public.reminder_log to authenticated;
grant select, insert, update, delete on public.reminder_log to service_role;
