-- Agent access and all-or-nothing writes.
--
-- * agent_keys: access keys for agents (MCP clients) acting for a household. Only a
--   SHA-256 hash is stored; the key itself is shown once in Settings.
-- * change_log: what agents changed, with the email or message it came from.
-- * cardfolio_* functions: multi-step writes (new card, product change, undo, credit
--   use) that used to be several browser requests now run as one transaction. They are
--   security invoker, so row-level security still applies to browser callers.

create table public.agent_keys (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  key_hash text not null unique,
  key_prefix text not null,
  created_by text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index idx_agent_keys_household on public.agent_keys(household_id);

create table public.change_log (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  actor text not null,
  action text not null,
  account_id bigint,
  summary text not null,
  source text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index idx_change_log_household on public.change_log(household_id, created_at desc);
create index idx_change_log_source on public.change_log(household_id, action, source) where source is not null;

alter table public.agent_keys enable row level security;
alter table public.change_log enable row level security;

-- Members create (hash only), list and revoke their household's keys in Settings.
create policy "members manage agent keys" on public.agent_keys for all
  using (public.is_cardfolio_member(household_id)) with check (public.is_cardfolio_member(household_id));
create policy "members read change log" on public.change_log for select
  using (public.is_cardfolio_member(household_id));

grant select, insert, update, delete on public.agent_keys to authenticated, service_role;
grant select on public.change_log to authenticated;
grant select, insert on public.change_log to service_role;

-- Credit uses recorded by an agent.
alter table public.credit_uses drop constraint if exists credit_uses_source_check;
alter table public.credit_uses add constraint credit_uses_source_check check (source in ('manual', 'import', 'plaid', 'agent'));

-- The next free card number for a person and card type, serialized so two writes can't take the same one.
create or replace function public.cardfolio_next_number(p_household uuid, p_person bigint, p_product bigint)
returns integer
language plpgsql
set search_path = ''
as $$
begin
  perform pg_advisory_xact_lock(hashtext(p_household::text || ':' || p_person || ':' || p_product));
  return coalesce((
    select max(number) from public.account_products
    where household_id = p_household and person_id = p_person and product_id = p_product
  ), 0) + 1;
end;
$$;

-- Returns the id of the card type named in `p_new` (reusing one with the same slug), or `p_product`.
create or replace function public.cardfolio_resolve_product(p_household uuid, p_product bigint, p_new jsonb)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_slug text;
  v_id bigint;
begin
  if p_new is null or p_new = 'null'::jsonb then
    if p_product is null then raise exception 'Choose a card type.'; end if;
    return p_product;
  end if;
  if coalesce(trim(p_new->>'name'), '') = '' then raise exception 'Name the new card type.'; end if;
  v_slug := lower(trim(coalesce(nullif(p_new->>'slug', ''), p_new->>'name')));
  select id into v_id from public.products where household_id = p_household and slug = v_slug;
  if v_id is not null then return v_id; end if;
  insert into public.products (household_id, slug, name, short_name, issuer, kind, annual_fee_cents)
  values (
    p_household, v_slug, trim(p_new->>'name'), nullif(trim(coalesce(p_new->>'short_name', '')), ''),
    coalesce(nullif(trim(coalesce(p_new->>'issuer', '')), ''), 'Other'),
    coalesce(p_new->>'kind', 'personal'), coalesce((p_new->>'annual_fee_cents')::integer, 0)
  )
  returning id into v_id;
  return v_id;
end;
$$;

-- A new account with its first product. `p_account` uses the accounts column names;
-- `p_number` null picks the next free number (approved cards only).
create or replace function public.cardfolio_add_card(
  p_household uuid, p_account jsonb, p_product bigint, p_new_product jsonb,
  p_number integer, p_annual_fee_cents integer, p_last4 text
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_product bigint := public.cardfolio_resolve_product(p_household, p_product, p_new_product);
  v_person bigint := (p_account->>'person_id')::bigint;
  v_status text := coalesce(p_account->>'status', 'pending');
  v_account bigint;
  v_number integer;
begin
  insert into public.accounts (
    household_id, person_id, applied_on, approved_on, opened_via, status, closed_on,
    bonus_amount, bonus_unit, bonus_spend_cents, bonus_months, bonus_earned, note
  ) values (
    p_household, v_person, (p_account->>'applied_on')::date, (p_account->>'approved_on')::date,
    coalesce(p_account->>'opened_via', 'applied'), v_status, (p_account->>'closed_on')::date,
    (p_account->>'bonus_amount')::integer, p_account->>'bonus_unit', (p_account->>'bonus_spend_cents')::integer,
    (p_account->>'bonus_months')::integer, coalesce((p_account->>'bonus_earned')::boolean, false), p_account->>'note'
  )
  returning id into v_account;

  if v_status in ('open', 'closed') then
    v_number := coalesce(p_number, public.cardfolio_next_number(p_household, v_person, v_product));
  end if;
  insert into public.account_products (household_id, account_id, person_id, product_id, number, started_on, change, annual_fee_cents, last4)
  values (
    p_household, v_account, v_person, v_product, v_number,
    coalesce((p_account->>'approved_on')::date, (p_account->>'applied_on')::date, current_date),
    'opened', coalesce(p_annual_fee_cents, 0), nullif(p_last4, '')
  );
  return v_account;
end;
$$;

-- An upgrade or downgrade: the current product ends on `p_date` and the new one starts.
create or replace function public.cardfolio_change_product(
  p_household uuid, p_account bigint, p_product bigint, p_new_product jsonb,
  p_date date, p_direction text, p_annual_fee_cents integer, p_last4 text
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_current public.account_products;
  v_product bigint;
  v_holding bigint;
begin
  if p_direction not in ('upgrade', 'downgrade') then raise exception 'Direction must be upgrade or downgrade.'; end if;
  select * into v_current from public.account_products
    where household_id = p_household and account_id = p_account and ended_on is null
    for update;
  if not found then raise exception 'That card has no current product.'; end if;
  if p_date < v_current.started_on then raise exception 'The change date must be after the current product started.'; end if;
  v_product := public.cardfolio_resolve_product(p_household, p_product, p_new_product);
  if v_product = v_current.product_id then raise exception 'The card is already that card type.'; end if;

  update public.account_products set ended_on = p_date where id = v_current.id;
  insert into public.account_products (household_id, account_id, person_id, product_id, number, started_on, change, annual_fee_cents, last4)
  values (
    p_household, p_account, v_current.person_id, v_product,
    public.cardfolio_next_number(p_household, v_current.person_id, v_product),
    p_date, p_direction, coalesce(p_annual_fee_cents, 0), coalesce(nullif(p_last4, ''), v_current.last4)
  )
  returning id into v_holding;
  return v_holding;
end;
$$;

-- Removes an account's most recent product change and reopens the product before it.
create or replace function public.cardfolio_undo_product_change(p_household uuid, p_account bigint)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_current public.account_products;
  v_previous bigint;
begin
  select * into v_current from public.account_products
    where household_id = p_household and account_id = p_account and ended_on is null
    for update;
  if not found or v_current.change = 'opened' then raise exception 'That card has no product change to undo.'; end if;
  delete from public.account_products where id = v_current.id;
  select id into v_previous from public.account_products
    where household_id = p_household and account_id = p_account
    order by started_on desc, id desc limit 1;
  update public.account_products set ended_on = null where id = v_previous;
  return v_previous;
end;
$$;

-- Replaces a card's use of a credit for one period; `p_amount_cents` null clears it.
create or replace function public.cardfolio_set_credit_use(
  p_household uuid, p_credit bigint, p_holding bigint, p_period text,
  p_amount_cents integer, p_used_on date, p_recorded_by text, p_source text
)
returns void
language plpgsql
set search_path = ''
as $$
begin
  delete from public.credit_uses
    where household_id = p_household and credit_id = p_credit and account_product_id = p_holding and period_key = p_period;
  if p_amount_cents is not null then
    insert into public.credit_uses (household_id, credit_id, account_product_id, period_key, amount_cents, used_on, recorded_by, source)
    values (p_household, p_credit, p_holding, p_period, p_amount_cents, coalesce(p_used_on, current_date), p_recorded_by, coalesce(p_source, 'manual'));
  end if;
end;
$$;

revoke all on function public.cardfolio_next_number(uuid, bigint, bigint) from public, anon;
revoke all on function public.cardfolio_resolve_product(uuid, bigint, jsonb) from public, anon;
revoke all on function public.cardfolio_add_card(uuid, jsonb, bigint, jsonb, integer, integer, text) from public, anon;
revoke all on function public.cardfolio_change_product(uuid, bigint, bigint, jsonb, date, text, integer, text) from public, anon;
revoke all on function public.cardfolio_undo_product_change(uuid, bigint) from public, anon;
revoke all on function public.cardfolio_set_credit_use(uuid, bigint, bigint, text, integer, date, text, text) from public, anon;
grant execute on function public.cardfolio_next_number(uuid, bigint, bigint) to authenticated, service_role;
grant execute on function public.cardfolio_resolve_product(uuid, bigint, jsonb) to authenticated, service_role;
grant execute on function public.cardfolio_add_card(uuid, jsonb, bigint, jsonb, integer, integer, text) to authenticated, service_role;
grant execute on function public.cardfolio_change_product(uuid, bigint, bigint, jsonb, date, text, integer, text) to authenticated, service_role;
grant execute on function public.cardfolio_undo_product_change(uuid, bigint) to authenticated, service_role;
grant execute on function public.cardfolio_set_credit_use(uuid, bigint, bigint, text, integer, date, text, text) to authenticated, service_role;
